p7zip script refactorings and enhancements
* Refactor and enhance the p7zip wrapper script:
  + update the p7zip script to the version from the contrib directory;
  + make it call either 7za or 7zr command, whichever one is available;
  + remove `if [ "$?" != 0 ]' statements, as they won't work with `set -e';
  + use the standard error for reporting;
  + implement the --stdout, --force, --keep options (closes: #656340,
    LP: #220646, #259239)
  + update p7zip(1) man page to shortly describe new options and give more
    details about the script's behavior.

diff --git a/debian/scripts/p7zip b/debian/scripts/p7zip
--- a/debian/scripts/p7zip
+++ b/debian/scripts/p7zip
@@ -1,144 +1,225 @@
 #!/bin/sh
 # gzip-like CLI wrapper for p7zip
-# version 2.0
+# version 3.0
 #
 # History
 #  2.0 :
 #    - support for -filename, "file name"
 #    - p7zip file1 file2 ...
+#  3.0 :  (robert@debian.org, March 2016)
+#    - use 7za or 7zr, whichever one is available
+#    - refactor the script for better readability
+#    - remove `"$?" != 0 ' checks that do not work with `set -e'
+#    - use stderr for error reporting
+#    - add support for -c, -f, -k options
 
 set -e
 
-usage ()
-  {
-    echo "Usage: $0 [-d] [-h|--help] [--] [ name ... ]"
-    echo ""
-    echo "    -h print this help"
-    echo "    -d decompress file"
-    echo "    -- treats  all  subsequent  arguments  as  file names, even if they start with a dash"
-    echo ""
-    exit 1
-  }
+# detect 7z program to use
+prg7z="`which 7za 2>/dev/null`" || \
+  prg7z="`which 7zr 2>/dev/null`" || \
+    { echo "$0: cannot find neither 7za nor 7zr command" >&2; exit 1; }
 
-doit()
+# global options
+f_compress=true
+f_keep=false
+f_force=false
+f_tostdout=false
+
+usage()
 {
-  compress=$1
-  file="$2"
-  
-  if [ "${file}" != "" ] ; then
-    if ${compress} ; then
-      if [ -f "${file}" ] ; then
-        rm -f -- "${file}.7z"
-        7za a -- "${file}.7z" "${file}"
-        if [ "$?" != "0" ] ; then
-          rm -f -- "${file}.7z"
-          exit 1
-        fi
-        rm -- "${file}"
-      else
-        exit 1
-      fi
-    else
-      case "${file}" in
-        *.7z)
-          if [ -f "${file}" ] ; then
-            7za x -- "${file}"
-            if [ "$?" != "0" ] ; then
-              exit 1
-            fi
-            rm -- "${file}"
-           else
-             exit 1
-           fi
-        ;;
-        *)
-          echo "$0: ${file}: unknown suffix"
-          exit 1
-        ;;
-      esac
-    fi
+  echo "Usage: $0 [options] [--] [ name ... ]"
+  echo ""
+  echo "Options:"
+  echo "    -c --stdout --to-stdout      output data to stdout"
+  echo "    -d --decompress --uncompress decompress file"
+  echo "    -f --force                   do not ask questions"
+  echo "    -k --keep                    keep original file"
+  echo "    -h --help                    print this help"
+  echo "    --                           treat subsequent arguments as file"
+  echo "                                 names, even if they start with a dash"
+  echo ""
+  exit 0
+}
+
+has_7z_suffix()
+{
+  case "$1" in
+    *.7z)
+      return 0
+      ;;
+    *)
+      return 1
+      ;;
+  esac;
+}
+
+make_tmp_file()
+{
+  P7ZIPTMP="${TMP:-/tmp}"
+  mktemp "${P7ZIPTMP}/p7zip.XXXXXXXX"
+}
+
+check_not_a_tty()
+{
+  if ! ${f_force} && ${f_compress} && tty <&1 >/dev/null ; then
+    echo "$0: compressed data not written to a terminal." >&2
+    echo "For help, type: $0 -h" >&2
+    exit 1
+  fi
+}
+
+compress_file()
+{
+  file="$1"
+
+  if ! ${f_force} && has_7z_suffix "${file}"; then
+    echo "$0: $file already has the 7z suffix" >&2
+    exit 1
+  fi
+
+  # compress to stdout via temporary file
+  if ${f_tostdout}; then
+    check_not_a_tty
+    tmp="`make_tmp_file`"
+    trap "rm -f -- ${tmp}" 0
+    rm -f -- "${tmp}"
+    "${prg7z}" a -si -- "${tmp}" < "${file}" >/dev/null && cat "${tmp}" || \
+      { echo "$0: failed to compress data to temporary file" >&2;  exit 1; }
+    rm -f -- "${tmp}"
     return 0
   fi
-  
-  P7ZIPTMP=${TMP:-/tmp}
-  tmp=`mktemp ${P7ZIPTMP}/p7zip.XXXXXXXX`
+
+  # compress to a file
+  if ! ${f_force} && [ -e "${file}.7z" ]; then
+    echo "$0: destination file ${file}.7z already exists" >&2
+    exit 1
+  fi
+
+  rm -f -- "${file}.7z"
+  flags=""
+  ${f_keep} || flags="$flags -sdel"
+  ! ${f_force} || flags="$flags -y"
+  "${prg7z}" a $flags -- "${file}.7z" "${file}" || {  rm -f -- "${file}.7z"; exit 1; }
+}
+
+
+decompress_file()
+{
+  file="$1"
+
+  has_7z_suffix "${file}" || { echo "$0: ${file}: unknown suffix" >&2; exit 1; }
+
+  # decompress to stdout
+  if ${f_tostdout}; then
+    # The following `| cat' pipe shouldn't be needed, however it is here to
+    # trick 7z not to complain about writing data to terminal.
+    "${prg7z}" x -so -- "${file}" | cat || exit 1
+    return 0;
+  fi
+
+  flags=""
+  ! ${f_force} || flags="$flags -y"
+  "${prg7z}" x $flags -- "${file}" || exit 1
+
+  # remove original file unless the archive contains more than one file
+  if ! ${f_keep} && "${prg7z}" l --  "${file}" 2>/dev/null | grep -q '^1 file,' 2>/dev/null; then
+    rm -f -- "${file}"
+  fi
+}
+
+process_file()
+{
+  file="$1"
+
+  # check if file exists and is readable
+  [ -r "${file}" ] || { echo "$0: cannot read ${file}" >&2; exit 1; }
+
+  if ${f_compress}; then
+    compress_file "${file}"
+  else
+    decompress_file "${file}"
+  fi
+}
+
+process_stdin()
+{
+  check_not_a_tty
+
+  tmp="`make_tmp_file`"
   trap "rm -f -- ${tmp}" 0
 
-  if ${compress} ; then
-    if tty > /dev/null ; then
-      echo "$0: compressed data not written to a terminal."
-      echo "For help, type: $0 -h"
-      exit 1
-    fi
-    rm -f -- ${tmp}
-    7za a -si -- ${tmp} >/dev/null
-    if [ "$?" != "0" ] ; then
-      exit 1
-    fi
-    cat ${tmp}
-  else
-    cat > ${tmp}
-    7za x -so -- ${tmp} 2>/dev/null | cat
-    if [ "$?" != "0" ] ; then
-      exit 1
-    fi
+  if ${f_compress}; then
+
+    rm -f -- "${tmp}"
+    "${prg7z}" a -si -- "${tmp}" >/dev/null && cat -- "${tmp}" || exit 1
+
+  else # decompress
+
+    cat > "${tmp}"
+    # The following `| cat' pipe shouldn't be needed, however it is here to
+    # trick 7z not to complain about writing data to terminal.
+    "${prg7z}" x -so -- "${tmp}" | cat || exit 1
   fi
-  
-  rm -f -- ${tmp}
-  return 0
+
+  rm -f -- "${tmp}"
 }
 
 
 ## MAIN
 
-compress=true
-flag=true
-file=""
-
-# make sure they're present, before we screw up
-for i in mktemp 7za rm cat tty ; do
-  if ! which $i > /dev/null ; then
-    echo "$0: $i: command not found"
-    exit 1
-  fi
-done
 
 # files and flags
 while [ "$#" != "0" ] ; do
   case "$1" in
-    -d)
-      compress=false # decompressing
+    -c|--stdout|--to-stdout)
+      f_tostdout=true
       ;;
-    -c)
-      echo "$0: ignoring $1 option (not yet implemented)"
+    -d|--decompress|--uncompress)
+      f_compress=false # decompressing
+      ;;
+    -f|--force)
+      f_force=true
       ;;
     -h|--help)
       usage
       ;;
+    -k|--keep)
+      keep=true
+      ;;
     --)
-      flag=false
       shift
       break
       ;;
+    -*)
+      echo "$0: ignoring unknown option $1" >&2
+      ;;
     *)
-	doit ${compress} "$1"
-        file="$1"
-    ;;
+      break
+      ;;
   esac
   shift
 done
 
+
+# make sure they're present, before we screw up
+for i in mktemp rm cat tty grep; do
+  if ! which $i >/dev/null ; then
+    echo "$0: $i: command not found" >&2
+    exit 1
+  fi
+done
+
+if [ "$#" = 0 ]; then
+  # compressing/decompressing using standard I/O
+  process_stdin
+  exit 0
+fi
+
 # only files now
 while [ "$#" != "0" ] ; do
-  doit ${compress} "$1"
-  file="$1"
+  process_file  "$1"
   shift
 done
 
-if [ "${file}" = "" ] ; then
-  # compressing/decompressing using standart I/O
-  doit ${compress}
-fi
-
 exit 0
-
